### PR TITLE
Upgrade moonlight-tv to 1.5.2

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
I am making a draft to show some advancement.

Enable host-nodejs to run moonlight-tv scripts during build. It is a required dependency: https://github.com/mariotaku/moonlight-tv/blob/v1.5.2/CMakeLists.txt#L107

@smx-smx Host-Python3 needs to be build with `BR2_PACKAGE_HOST_PYTHON3_BZIP2=y`. Do you know how this requirement can be defined in moonlight-tv package ?
(Don't hesitate to update my PR or take my change for another PR/commit)

The build passes on my computer but remotely it is failing due to OOM:
- local: `make clean sdk`
- remotely:
https://cirrus-ci.com/task/4573122547417088 reached `Container errored with 'OOMKilled'`.
image
I had to increase to `9GB`: https://cirrus-ci.com/task/6464635715977216 but it still failing
`10GB`: https://cirrus-ci.com/task/6055008713048064 still failing
`12GB`: https://cirrus-ci.com/task/5627897300910080 still failing
`16GB`: https://cirrus-ci.com/task/6433599275663360 still failing

I am trying with 17GB. That's weird that nodejs is taking so much memory.

### CODE REVIEW

**Comment by GuillaumeSmaha** [comment]
Finally works with 17GB.

**Comment by GuillaumeSmaha** [comment]
It seems building nodejs need a lot of memory

**Comment by smx-smx** [comment]
Let's see if this is sustainable. Thanks for the effort in tracking this down 👍

**Comment by GuillaumeSmaha** [comment]
No luck for the CI on master branch: Instance was rescheduled: https://cirrus-ci.com/task/6246328056414208

**Comment by smx-smx** [comment]
I think i will just get rid of moonlight-tv and host-nodejs in the lgtv default preset.
It was used as a sample to see if there were all necessary components to build moonlight, but it's not really necessary as part of an SDK/toolchain and it's putting too much burden on the infrastructure.

**Comment by GuillaumeSmaha** [comment]
> I think i will just get rid of moonlight-tv and host-nodejs in the lgtv default preset. It was used as a sample to see if there were all necessary components to build moonlight, but it's not really necessary as part of an SDK/toolchain and it's putting too much burden on the infrastructure.

Yes, good idea and it can still be recompiled by ourself if it is needed

**Comment by smx-smx** [comment]
Done

**Pull request merged**
